# Generated by Django 4.2.7 on 2023-12-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='category_img/', verbose_name='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('mojoudi', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='menu_item_img/', verbose_name='Menu_Item_Main_Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='cafemenu.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_image', models.ImageField(blank=True, null=True, upload_to='menu_item_img/', verbose_name='Menu_Item_Image')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cafemenu.menuitem')),
            ],
        ),
    ]
